$(document).ready(function(){
	$(document).click(function(){
		$("#logSignContainer").css({"width":"200px"});
		$("#signupBox").css({"visibility":"hidden"});
		$("#signupBox").css({"opacity":"0"});
		$("#loginBox").css({"visibility":"hidden"});
		$("#loginBox").css({"opacity":"0"});
		$("#loginContainer").css({"background-color":"#444444"});
		$("#signupContainer").css({"background-color":"#444444"});
	});
	$("#loginContainer").click(function(event){
		$("#logSignContainer").css({"width":"400px"});
		$("#loginContainer").css({"background-color":"#333333"});
		$("#signupContainer").css({"background-color":"#444444"});
		$("#signupBox").css({"width":"350px"});
		$("#signupBox").css({"visibility":"hidden"});
		$("#signupBox").css({"opacity":"0"});
		$("#loginBox").css({"width":"350px"});
		$("#loginBox").css({"visibility":"visible"});
		$("#loginBox").css({"opacity":"1"});
		event.stopPropagation();
	});
	$("#signupContainer").click(function(event){
		$("#logSignContainer").css({"width":"400px"});
		$("#signupContainer").css({"background-color":"#333333"});
		$("#loginContainer").css({"background-color":"#444444"});
		$("loginBox").css({"width":"350px"});
		$("#loginBox").css({"visibility":"hidden"});
		$("#loginBox").css({"opacity":"0"});
		$("#signupBox").css({"width":"350px"});
		$("#signupBox").css({"visibility":"visible"});
		$("#signupBox").css({"opacity":"1"});
		event.stopPropagation();
	});

	$("#signupBox").click(function(event){
		$("#logSignContainer").css({"width":"400px"});
		$("#signupBox").css({"visibility":"visible"});
		$("#signupBox").css({"opacity":"1"});
		$("#signupContainer").css({"background-color":"#333333"});
		event.stopPropagation();
	});
	$("#loginBox").click(function(event){
		$("#logSignContainer").css({"width":"400px"});
		$("#loginBox").css({"visibility":"visible"});
		$("#loginBox").css({"opacity":"1"});
		$("#loginContainer").css({"background-color":"#333333"});
		event.stopPropagation();
	});
});